### ISSUE TITLE
Doc2Vec trained model file missing and download error

### ISSUE THREAD

**Issue by bryanchun** [sb1992/NETL-Automatic-Topic-Labelling-#7]
Hi all,

I am having difficulty in trying to run this system on a sample csv topic list I created. Following the README, I have downloaded the trained models for Doc2Vec and Word2Vec and extract them to `pre_trained_models` accordingly:

```
pre_trained_models
├── doc2vec
│   ├── docvecmodel.d2v
│   ├── docvecmodel.d2v.syn0.npy
│   └── docvecmodel.d2v.syn1neg.npy
├── readme.txt
└── word2vec
    └── word2vec
```

With all the libraries (at suitable version for example gensim==1.0.1) and support files (PageRank and SVM Rank) in place, I tried to run the program in `model_run/`:

```
$ python3 get_labels.py -cg -us -s

Extracting candidate labels
Traceback (most recent call last):
  File "cand_generation.py", line 54, in <module>
    model1 =Doc2Vec.load(args.doc2vecmodel)
  File "/Users/Bryan/cx4242/NETL-Automatic-Topic-Labelling-/env/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1270, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/Users/Bryan/cx4242/NETL-Automatic-Topic-Labelling-/env/lib/python3.6/site-packages/gensim/utils.py", line 267, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/Users/Bryan/cx4242/NETL-Automatic-Topic-Labelling-/env/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1294, in _load_specials
    super(Word2Vec, self)._load_specials(*args, **kwargs)
  File "/Users/Bryan/cx4242/NETL-Automatic-Topic-Labelling-/env/lib/python3.6/site-packages/gensim/utils.py", line 286, in _load_specials
    getattr(self, attrib)._load_specials(cfname, mmap, compress, subname)
  File "/Users/Bryan/cx4242/NETL-Automatic-Topic-Labelling-/env/lib/python3.6/site-packages/gensim/utils.py", line 298, in _load_specials
    val = np.load(subname(fname, attrib), mmap_mode=mmap)
  File "/Users/Bryan/cx4242/NETL-Automatic-Topic-Labelling-/env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'pre_trained_models/doc2vec/docvecmodel.d2v.docvecs.doctag_syn0.npy'
Executing Unsupervised model
Traceback (most recent call last):
  File "unsupervised_labels.py", line 27, in <module>
    with open(args.output_candidates,'r') as k:
FileNotFoundError: [Errno 2] No such file or directory: 'output_candidates'
Executing Supervised Model
page Rank models loaded
Traceback (most recent call last):
  File "supervised_labels.py", line 43, in <module>
    with open(args.output_candidates,'r') as k:
FileNotFoundError: [Errno 2] No such file or directory: 'output_candidates'
```

Apparently `model_run/pre_trained_models/doc2vec/docvecmodel.d2v.docvecs.doctag_syn0.npy` is missing. I am assuming `output_candidates/` will be autogenerated if the previous errors are gone. Unfortunately I don't find files other than those 3 listed in the file tree to extract.

When I try to re-download and verify, box.com throws me error on about half of the download process.
<img width="700" alt="Screenshot 2019-03-30 10 27 17" src="https://user-images.githubusercontent.com/22416129/55277426-6e636f00-52d6-11e9-981e-76fcbd26fc25.png">
And I have deleted the previous `.tgz` due to not enough disk space.

---

So my questions are

- Is there a mirror download link for Doc2Vec trained model? Or the link can be used normally?
- Is `docvecmodel.d2v.docvecs.doctag_syn0.npy` really needed? If so, how can I obtain it?

Thank you very much for your kind attention.

**Comment by bryanchun** [comment]
I resolved this by realising that it is due to limits of my disk to transfer more than 4GB of data. On downloading the .tgz successfully on to a hard disk, uncompressing it gives all the needed documents. So basically the file becomes corrupted in my first attempt.
