### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'predictionstemp'

### ISSUE THREAD

**Issue by srujana-tak** [sb1992/NETL-Automatic-Topic-Labelling-#8]
Executing Supervised Model
page Rank models loaded
Data Gathered for supervised model
letter trigram feature
All features generated
sh: support_files/svm_rank_classify: Permission denied
Traceback (most recent call last):
  File "supervised_labels.py", line 249, in <module>
    get_predictions(test_list,test_chunk_size)
  File "supervised_labels.py", line 219, in get_predictions
    h =open("predictionstemp")
IOError: [Errno 2] No such file or directory: 'predictionstemp'

**Comment by srujana-tak** [comment]
Any help on how to solve this while executing supervised_labels.py file

**Comment by thanhkhocnhe** [comment]
your problem appear when you run on Windown, File predictionstemp will be create after run file binary svm_rank_classify (view code). On win, this file invalid. therefor i recommend you to run it on Linux :)

**Comment by uzaymacar** [comment]
The same issue persists in Linux for me.
